name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install build tools
      run: |
        sudo apt update
        sudo apt install -y zip unzip openjdk-17-jdk python3-pip build-essential ccache libncurses5 libstdc++6 libffi-dev libssl-dev libsqlite3-dev zlib1g-dev

    - name: Install Buildozer
      run: |
        pip install --upgrade pip
        pip install buildozer cython virtualenv

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: mahjong-apk
        path: bin/*.apk
